# Intro to NumPy


## Python Tuple and Lists

- The key difference between the tuples and lists is that while the tuples are <b>immutable</b> objects the lists are <b>mutable</b>. This means that tuples cannot be changed while the lists can be modified.
- Tuples are more memory efficient than the lists.
- When it comes to the time efficiency, tuples have a slight advantage over the lists especially when we consider lookup value.
- If you have data that shouldn’t change, you should choose tuple data type over lists.

In [16]:
import time
import sys, platform

In [17]:
a_list = list()
a_tuple = tuple()

a_list = [1,2,3,4,5]
a_tuple = (1,2,3,4,5)

print(sys.getsizeof(a_list))
print(sys.getsizeof(a_tuple))

104
80


As you can see from the output of the above code snippet, the memory required for the identical list and tuple objects is different.

In [3]:
print(platform.python_version())

start_time = time.time()
b_list = list(range(10000000))
end_time = time.time()
print("Instantiation time for LIST:", end_time - start_time)

start_time = time.time()
b_tuple = tuple(range(10000000))
end_time = time.time()
print("Instantiation time for TUPLE:", end_time - start_time)

start_time = time.time()
for item in b_list:
  aa = b_list[20000]
end_time = time.time()
print("Lookup time for LIST: ", end_time - start_time)

start_time = time.time()
for item in b_tuple:
  aa = b_tuple[20000]
end_time = time.time()
print("Lookup time for TUPLE: ", end_time - start_time)

3.11.5
Instantiation time for LIST: 0.1813497543334961
Instantiation time for TUPLE: 0.19156503677368164
Lookup time for LIST:  0.5050816535949707
Lookup time for TUPLE:  0.42401790618896484


In [19]:
a=[1,'apple', 4.5]
print(a)

[1, 'apple', 4.5]


When it comes to the time efficiency, again tuples have a slight advantage over the lists especially when we consider lookup value.

# What is a Numpy array?
[NumPy](https://numpy.org/doc/1.26/index.html) is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data. 

## Some important points about Numpy arrays:

- We can create an N-dimensional array in Python using Numpy.array().
- The array is by default Homogeneous, which means data inside an array must be of the same Datatype.
- Element-wise operation is possible.
- Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
- Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.

## Representation of Numpy array


In [ ]:
!pip install numpy

In [21]:
import numpy as np

### Single Dimensional Numpy Array

In [22]:
sd_arr = np.array([1, 2, 3])
print(sd_arr)

[1 2 3]


### Multi-dimensional Numpy Array

In [23]:
md_arr = np.array([(1, 2, 3), (4, 5, 6)])
print(md_arr)

[[1 2 3]
 [4 5 6]]


## List Memory Allocation
![py-list](./assets/py-list.png)

## Numpy Memory Allocation
![numpy-list](./assets/py-numpy.png)

## Array creation functions

[numpy.arange](https://numpy.org/doc/1.26/reference/generated/numpy.arange.html#numpy.arange) creates arrays with regularly incrementing values

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

[numpy.linspace](https://numpy.org/doc/1.26/reference/generated/numpy.linspace.html#numpy.linspace) will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [26]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

[np.eye(n, m)](https://numpy.org/doc/1.26/reference/generated/numpy.eye.html#numpy.eye) defines a 2D identity matrix

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

[numpy.diag](https://numpy.org/doc/1.26/reference/generated/numpy.diag.html#numpy.diag) can define either a square 2D array with given values along the diagonal

In [29]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Similary there are np.ones np.zero etc