In [35]:
!pip install ucimlrepo

You should consider upgrading via the '/Users/tanisha.belkar/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip' command.


In [18]:
!pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 10.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 KB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.9/256.9 KB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 8.5 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 10.1 MB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/Users/tanisha.belkar/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip' command.


In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
import numpy as np
from ucimlrepo import fetch_ucirepo 
import matplotlib.pyplot as plt 

## Logistic Regression

In [69]:
phishing_websites = fetch_ucirepo(id=327) 

X = phishing_websites.data.features 
y = phishing_websites.data.targets 

X.head()

having_ip_address  url_length  shortining_service  having_at_symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  prefix_suffix  having_sub_domain  sslfinal_state  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   domain_registration_length  favicon  ...  rightclick  popupwindow  iframe  \
0                          -1        1  ...           1            1       1   
1                          -1        1  ...           1            1       1   
2                          -1        1  ...           1            1       1   
3                           1        1  ...           1            1       1   
4                          -1        1  ...           1           -1       1   

   age_of_domain  dnsrecord  web_traffic  page_rank  google_index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   links_pointing_to_page  statistical_report  
0                       1                  -1  
1                       1                   1  
2                       0                  -1  
3                      -1                   1  
4                       1                   1  

[5 rows x 30 columns]

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [73]:
def get_results(model):
    model.fit(X_train, y_train['result'])
    y_pred = model.predict(X_test)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print(accuracy)
    print(cnf_matrix)
    

In [77]:
logreg = LogisticRegression()
get_results(logreg)

0.9225759768451519
[[1075  124]
 [  90 1475]]


## Decision trees

In [78]:
from sklearn.tree import DecisionTreeClassifier

In [79]:
clf = DecisionTreeClassifier()
get_results(clf)

0.9620115774240231
[[1142   57]
 [  48 1517]]


## Random forest

In [80]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
get_results(rf)

0.9757597684515196
[[1155   44]
 [  23 1542]]
